apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: casual-sst

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml      # comment out if you don't want the included ingress

# Override the image tag at apply time:
#   kustomize edit set image schnsrw/casual-sst:cuda-0.0.1
#   kubectl apply -k deploy/k8s/
images:
  - name: schnsrw/casual-sst
    newTag: cuda-latest
